# Site settings
title: Hack Clock
email: john@deckerego.net
description: > # this means to ignore newlines until "baseurl:"
  A hackable alarm clock, made for experimentation to learn GPIO and programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hackclock.deckerego.net" # the base hostname & protocol for your site
twitter_username: deckerego
github_username:  deckerego
hackaday_url: http://hackaday.io/hacker/5116-deckerego
hackaday_username: deckerego

# Build settings
markdown: kramdown
